apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster1
  region: us-east-1

managedNodeGroups: # this is also completely managed by AWS
  - name: spot
    instanceType: m5.large
    # your K8 node can be anytime taken back by AWS
    spot: true
    availabilityZones:
    - us-east-1c
    desiredCapacity: 3
    ssh:
      publicKeyName: centos8 # replace this with your keypair exists in AWS.